# -*- coding: utf-8 -*-
"""Benjamin Nikholas_Tugas 4_Modul 1_6 Mei 2024.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Pqe3gWL-WtZzAXwI2QwBjwSKwoXKEvu5

> Benjamin Nikholas

> Data Science / JCSDOL-014

> Modul 1 - Tugas 4

> 6 Mei 2024
---
---

#1

Buatlah suatu program untuk menghitung nilai Factorial menggunakan While Loop

> Input : Masukkan Angka :

> Output : Nilai Faktorial dari … adalah …

> Ketentuan
* Angka harus di atas 0, keluarkan notifikasi
* Input tidak bisa menerima string, keluarkan notifikasi
"""

while True:
  num = input('Masukkan Angka: ')

  if not num.isdigit():
      print('Input tidak bisa menerima string.')
  else:
      angka = int(num)

      if angka <= 0:
          print('Angka harus di atas 0.')
      else:
          faktorial = 1
          i = 1

          while i <= angka:
              faktorial *= i
              i += 1

          print(f'Nilai Faktorial dari {angka} adalah {faktorial}')
          break

"""#2

Buat program untuk menghitung total angka dari inputan angka
> Input : Masukkan Angka : …

> Output : Total angka dari inputan : …
"""

num = input("Masukkan Angka: ")

total = 0

for i in num:
    if i.isdigit():
        total += int(i)

print("Total angka dari inputan:", total)

"""#3
> Buat program untuk menghitung Total semua angka antara 1 dan 100 yang habis di bagi 3
dan 5
"""

total = 0

for num in range(1, 101):
    if num % 3 == 0 and num % 5 == 0:
        total += num

print(f'Total semua angka antara 1 dan 100 yang habis dibagi oleh 3 dan 5 adalah: {total}')

"""#4

Buat program untuk menghitung nilai range Inputan, dengan ketentuan Nilai angka Genap
sendiri dan nilai angka ganjil sendiri
> Input :
* Masukkan Range awal :
* Masukkan Range akhir :

> Output :
* Jumlah Angka genap dari …. Hingga …. Adalah … dan jumlah nilai ganjil adalah ….
"""

start_range = int(input('Masukkan Range awal: '))
end_range = int(input('Masukkan Range akhir: '))

even_count, odd_count = 0, 0

for num in range(start_range, end_range + 1):
    if num % 2 == 0:
        even_count += 1
    else:
        odd_count += 1

print(f'Jumlah Angka genap dari {start_range} hingga {end_range} adalah {even_count} dan jumlah nilai ganjil adalah {odd_count}')