# -*- coding: utf-8 -*-
"""Benjamin Nikholas_Tugas 7_Modul 1_14 Mei 2024 (Team Assignment).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EGPk12WPg9zIXp6-ma50f-8P1XBAVT0P

> Benjamin Nikholas

> Data Science / JCSDOL-014

> Modul 1 - Tugas 7

> 14 Mei 2024

> Teams Assignment (Kelompok 7):

* Benjamin Nikholas
* Tirza Hidayati
* Indah Astary Suwandi
* Febby Putri Milenia Piter

---
---

#1
"""

def time_convert(seconds):
    if not isinstance(seconds, int) or seconds < 0 or seconds > 359999:
        return 'Invalid Input!'

    hours = seconds // 3600
    minutes = (seconds % 3600) // 60
    seconds = seconds % 60

    return f'{hours:02}:{minutes:02}:{seconds:02}'

def start_converter():
    while True:
        user_input = input('Masukkan detik: ')

        try:
            seconds = int(user_input)
        except ValueError:
            print('Invalid Input!')
            continue

        result = time_convert(seconds)
        print(f'Konversi: {result}')
        break

start_converter()

"""#2 Indah"""

def npwp_verification(npwp):
    clean_npwp = npwp.replace('.', '').replace('-', '')
    if len(clean_npwp) != 15:
        return 'Kode seri NPWP tidak valid!\nKode seri NPWP ini tidak valid dikarenakan lebih dari 15 digit angka.'

    if not clean_npwp.isdigit():
        return 'Kode seri NPWP tidak valid!\nKode seri NPWP ini tidak valid dikarenakan terdapat karakter bukan angka di dalamnya.'

    if len(npwp) != 20 or npwp[2] != '.' or npwp[6] != '.' or npwp[10] != '.' or npwp[12] != '-' or npwp[16] != '.':
        return 'Kode seri NPWP tidak valid!\nKode seri NPWP ini tidak valid dikarenakan tidak mengikuti format baku: 99.999.999.9-999.999.'

    wp_identity = int(clean_npwp[:2])
    regist_num = clean_npwp[2:8]
    safety = clean_npwp[8]
    kpp_code = clean_npwp[9:12]
    wp_status = clean_npwp[12:]

    if wp_identity < 1 or wp_identity > 9:
        return 'Kode seri NPWP tidak valid!\nKode seri NPWP ini tidak valid dikarenakan 2 digit pertama hanya bisa diisi 01 sampai 09.'

    if wp_identity in range(1, 4):
        identitas_keterangan = 'Wajib Pajak Badan'
    elif wp_identity in [4, 6]:
        identitas_keterangan = 'Wajib Pajak Pengusaha'
    elif wp_identity == 5:
        identitas_keterangan = 'Wajib Pajak Karyawan'
    elif wp_identity in range(7, 10):
        identitas_keterangan = 'Wajib Pajak Orang Pribadi'
    else:
        return 'Kode seri NPWP tidak valid!\nKode seri NPWP ini tidak valid dikarenakan 2 digit pertama hanya bisa diisi 01 sampai 09.'

    res = f'''Kode seri NPWP valid!
 Identitas Wajib Pajak: {wp_identity} {identitas_keterangan}
 Nomor Registrasi: {regist_num}
 Alat Pengaman: {safety}
 Kode KPP: {kpp_code}
 Status Wajib Pajak: {wp_status}\n'''

    return res

# testcase
testcase_list = ['99.999.999.9-999.999',
                 '091234565623179',
                 '09.123.456.A-123.123',
                 '09.265.796.5-235.6987',
                 '05.885.434.4-215.000']

for i in testcase_list:
  print(npwp_verification(i))

"""#3"""

def urai(s):
    result = ''
    for i in range(1, len(s) + 1):
        result += s[:i]
    return result

def rajut(s):
    n = 0
    while (n * (n + 1)) // 2 < len(s):
        n += 1
    if (n * (n + 1)) // 2 != len(s):
        return "Invalid input"

    original_str = s[(n * (n - 1)) // 2:]

    return original_str

print(urai('Code'))
print(urai('Python'))
print(urai('Purwadhika'))

print(rajut('CCoCodCode'))
print(rajut('PPyPytPythPythoPython'))
print(rajut('PPuPurPurwPurwaPurwadPurwadhPurwadhiPurwadhikPurwadhika'))