# -*- coding: utf-8 -*-
"""Benjamin Nikholas_Tugas 6_Modul 1_13 Mei 2024.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iZQ78Tx5PWzEcNPFD-O0PJFpsA5hPDhd

> Benjamin Nikholas

> Data Science / JCSDOL-014

> Modul 1 - Tugas 6

> 13 Mei 2024
---
---

Email Verification

Input :
Masukkan Email :

Output :
Sesuai dg Kondisi
Kondisi Valid Jika :
- Memiliki Format Nama User@Nama Hosing eksistensi
- Nama user hanya Boleh Huruf, Angka, underscore(_) dan dot(.)
- Nama user hanya Boleh di awali dg Huruf atau Angka
- Nama Hosting hanya boleh huruf atau kombinasi huruf dan angka
- Nama Ekstensi Hanya boleh Huruf dan maksimal 5 Karakter
- Simbol Karakter Khusus Tidak bisa diterima
- Jumlah @ hanya boleh 1
- .co.id , .co.my atau .co.sg ==> ini dianggap sebagai 2 ekstensi, jadi masing-masing harus mengikuti aturan ekstensi

Contoh Output :
"Alamat Email yg anda Masukkan Valid"

Jika Tidak Valid, Keluar Notifikasi dengan alasannya:

Email Tidak Valid, Alasan
Alasan :
- Format Email Salah (Misal Tidak ada @, atau tidak ada .ekstensi)
- Format Username yg anda masukkan salah
- Format Hosting yang anda masukkan salah
- Format Ekstensi yg anda masukkan Salah

-------------------------------------------------------------------------------

Contoh Email :
Valid
andre@gmail.com
joni_99@yahoo.com
andy.134@city.com
steve_roger.77@avengers01.space

Invalid
andre345@gmail
andre%$^@gmail.com
john@yah%%oo.com
tony_stark@stark.corpora
"""

def verify_email(email):

    parts = email.split('@')

    if len(parts) != 2:
        return 'Email Tidak Valid, Alasan: Format Email Salah'

    username, domain = parts

    if username == '':
        return 'Email Tidak Valid, Alasan: Format Username yang anda masukkan salah'

    # Username Validation
    if not (username[0].isalnum()):
        return 'Email Tidak Valid, Alasan: Format Username yang anda masukkan salah'
    elif not all(c.isalnum() or c in ['_', '.'] for c in username):
        return 'Email Tidak Valid, Alasan: Format Username yang anda masukkan salah'

    # Domain Validation
    domain_parts = domain.split('.')

    if len(domain_parts) not in [2, 3]:
        return 'Email Tidak Valid, Alasan: Format Domain yang anda masukkan salah'

    # Hosting Name Validation
    if domain_parts[0] == '':
        return 'Email Tidak Valid, Alasan: Nama Hosting yang anda masukkan salah'
    elif not all(c.isalnum() or c in ['_', '.'] for c in domain_parts[0]):
        return 'Email Tidak Valid, Alasan: Nama Hosting yang anda masukkan salah'

    # Extention Validation
    for part in domain_parts[1:]:
        if not part or not part.isalpha() or not (2 <= len(part) <= 5):
            return 'Email Tidak Valid, Alasan: Format Ekstensi yang anda masukkan Salah'

    return 'Alamat Email yang anda Masukkan Valid'

input_testcase = ['andre@gmail.',
                  '@gmail.com',
                  '(bayu)@gmail.com',
                  'andre@@gmail',
                  'bima@gmail..',
                  'bisa@g345.45.com',
                  'gandi@gm41l.co.12',
                  'benji@gmail.com']

for test in input_testcase:
  print(verify_email(test))

