# -*- coding: utf-8 -*-
"""Benjamin Nikholas_Tugas 10_Modul 1_20 Mei 2024.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RVXUNEdZvYoqGQrHgUQNPXGgQs6Aiupz

> Benjamin Nikholas

> Data Science / JCSDOL-014

> Modul 1 - Tugas 10

> 20 Mei 2024
---
---

# 1 Calculator
"""

def calculator():
    def get_input(prompt):
        while True:
            user_input = input(prompt)
            try:
                num = float(user_input)
                if num.is_integer():
                    return int(num)
                else:
                    return num
            except ValueError:
                print('Input Not Valid')

    num1 = get_input('Masukkan Angka 1: ')
    num2 = get_input('Masukkan Angka 2: ')

    while True:
        opt = input('Masukkan operator [+/-*] : ')
        if opt in '+/-*':
            break
        else:
            print('Invalid Operator')

    if opt == '+':
        print(f'Hasil dari {num1} {opt} {num2} = {num1 + num2}')
    elif opt == '-':
        print(f'Hasil dari {num1} {opt} {num2} = {num1 - num2}')
    elif opt == '*':
        print(f'Hasil dari {num1} {opt} {num2} = {num1 * num2}')
    elif opt == '/':
        if num2 != 0:
            print(f'Hasil dari {num1} {opt} {num2} = {num1 / num2}')
        else:
            print("Pembagian dengan nol tidak valid")
    else:
        print('Invalid Operator')

calculator()

"""#2 Encode Decode Morse"""

morse_dict_encoder = {
    'A': '.-', 'B': '-...', 'C': '-.-.', 'D': '-..', 'E': '.', 'F': '..-.',
    'G': '--.', 'H': '....', 'I': '..', 'J': '.---', 'K': '-.-', 'L': '.-..',
    'M': '--', 'N': '-.', 'O': '---', 'P': '.--.', 'Q': '--.-', 'R': '.-.',
    'S': '...', 'T': '-', 'U': '..-', 'V': '...-', 'W': '.--', 'X': '-..-',
    'Y': '-.--', 'Z': '--..', '1': '.----', '2': '..---', '3': '...--',
    '4': '....-', '5': '.....', '6': '-....', '7': '--...', '8': '---..',
    '9': '----.', '0': '-----', ' ': '|'
}

morse_dict_decoder = {}
for key, value in morse_dict_encoder.items():
    morse_dict_decoder[value] = key

def morse_translator(input_text):
    # Check if input is Morse code
    if all(char in '.-| ' for char in input_text):
        words = input_text.split('|')
        try:
            decoded_message = ''.join(morse_dict_decoder[code.strip()] for code in words if code.strip())
            return f'Kode Morse yg anda masukkan {input_text} jika diubah menjadi kata-kata Menjadi {decoded_message}'
        except KeyError:
            return 'Input kode Morse tidak valid.'

    # Check if input is valid text (only alphanumeric characters and spaces)
    elif all(char.isalnum() or char.isspace() for char in input_text):
        encoded_message = ' | '.join(morse_dict_encoder[char] for char in input_text.upper())
        return f'Kata yg anda masukkan adalah {input_text} Jika diubah menjadi Kode Morse Menjadi {encoded_message}'

    else:
        return 'Input tidak valid. Hanya menerima alfabet, angka, dan spasi untuk teks biasa.'

input_text = input('Masukkan kata: ')
print(morse_translator(input_text))