# -*- coding: utf-8 -*-
"""Benjamin Nikholas_Tugas 9_Modul 1_16 Mei 2024.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lAfNhCn6X7NdYGuRfyVlqADCMyDlKqln

> Benjamin Nikholas

> Data Science / JCSDOL-014

> Modul 1 - Tugas 9

> 16 Mei 2024
---
---
"""

def rotate_matrix(matrix, option):
    n = len(matrix)

    result = []
    for _ in range(n):
        result.append([0] * n)

    if option == 1:
        for i in range(n):
            for j in range(n):
                # print(n-1-j, i, j)
                # print(matrix[n-1-j][i], matrix[n-1-j])
                result[i][j] = matrix[n-1-j][i]
    elif option == 2:
        for i in range(n):
            for j in range(n):
                # print(n-1-i, n-1-j, i, j)
                # print(matrix[n-1-i][n-1-j], matrix[n-1-i])
                result[i][j] = matrix[n-1-i][n-1-j]
    elif option == 3:
        for i in range(n):
            for j in range(n):
                # print(n-1-i, i, j)
                # print(matrix[j][n-1-i], matrix[j])
                result[i][j] = matrix[j][n-1-i]
    else:
        return "Invalid option"

    return result

# Testcase
Angka = [
    [1, 2, 3, 4, 5],
    [6, 7, 8, 9, 10],
    [11, 12, 13, 14, 15],
    [16, 17, 18, 19, 20],
    [21, 22, 23, 24, 25]
]

option = int(input("Masukkan angka 1-3: "))
result = rotate_matrix(Angka, option)
for row in result:
    print(row)