# -*- coding: utf-8 -*-
"""Benjamin Nikholas_Tugas 18_Modul 2_5 Juni 2024.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wl085zXeLiIle0vyVvrkPNub4QBxl-ao

> Benjamin Nikholas

> Data Science / JCSDOL-014

> Modul 2 - Tugas 18

> 5 Juni 2024
---
---

## **Latihan Pandas 1**

## Jangan di-run! Copy dulu file ini, kemudian jawab di file copy tersebut

**Membuat DataFrame**

Ikuti semua petunjuk yang harus dilakukan di bawah ini.

**Step 1. Import library yang dibutuhkan.**
"""

import numpy as np
import pandas as pd

"""**Step 2. Buat dictionary untuk membuat DataFrame berjumlah 5 key dan masing-masing key memiliki value berupa list dengan 10 item.**"""

data = {
    'Nama': ['Adele', 'Beyonce', 'Camila', 'Donald', 'Eminem', 'Ferguson', 'Gaga', 'Hillary', 'Indro', 'Joko'],
    'Umur': [24, 25, 30, 32, 28, 24, 29, 31, 30, 29],
    'Gender': ['Wanita', 'Wanita', 'Wanita', 'Pria', 'Pria', 'Pria', 'Wanita', 'Wanita', 'Pria', 'Pria'],
    'Pekerjaan': ['Data Analyst', 'Data Engineer', 'Data Scientist', 'Data Scientist', 'Data Analyst',
                  'Data Engineer', 'ML Engineer', 'ML Researcher', 'BI Analyst', 'Data Analyst'],
    'Domisili': ['Jakarta', 'Tangerang', 'Jakarta', 'Bandung', 'Jakarta', 'Surabaya',
                 'Bandung', 'Yogyakarta', 'Jakarta', 'Tangerang']
}

df = pd.DataFrame(data)
df

"""**Step 3. Ubah urutan kolom tersebut menjadi seperti berikut: Nama, Gender, Umur, Domisili, Pekerjaan.**"""

# new_df = pd.DataFrame([df.Nama, df.Gender, df.Umur, df.Domisili, df.Pekerjaan]).T

new_df = df.reindex(columns = ['Nama', 'Gender', 'Umur', 'Domisili', 'Pekerjaan'])
new_df

"""**Step 4. Tambahkan 1 kolom baru bernama 'Hobi' dan isikan datanya seperti output berikut.**"""

df['Hobi'] = ['Gaming', 'Masak',
              'Baca', 'Gaming',
              'Futsal', 'Traveling',
              'Basket', 'Traveling',
              'Gaming', 'Futsal']

df

"""**Soal Lanjutan**

**5. Gunakan .iloc untuk mengambil data Donald, Ferguson, Hillary**
"""

df.iloc[[3, 5, 7]]

"""**6. Gunakan .loc untuk menampilkan domisili dan pekerjaan dari Camila dan Indro (termasuk kolom nama)**

"""

df.loc[df.Nama.isin(['Camila', 'Indro']),
       ['Nama', 'Domisili', 'Pekerjaan']]

"""**7. Gunakan .iloc untuk menampilkan semua data dari Hillary dan Joko**"""

df.iloc[[7, 9]]

"""**8. Siapa sajakah yang berumur lebih dari 30 tahun?**"""

df[df.Umur > 30]

"""**9. Siapa sajakah yang berumur kurang dari 30 tahun dan hobinya Gaming?**"""

df[(df.Umur < 30) & (df.Hobi == 'Gaming')]

"""**10. Tampilkan nama orang yang pekerjaannya adalah Data Analyst! Tampilkan kolom nama saja dalam bentuk Series!**"""

df.loc[df.Pekerjaan == 'Data Analyst', 'Nama']

"""**11. Apa saja pekerjaan orang-orang yang berdomisili di Jakarta? Tampilkan nama dan pekerjaannya!**"""

df.loc[df.Domisili == 'Jakarta',
 ['Nama', 'Pekerjaan']]

"""**12. Apa saja hobi para wanita yang ada di dataset? Tampilkan hanya kolom Nama, Hobi, Umur secara berurutan!**"""

df.loc[df.Gender == 'Wanita',
 ['Nama', 'Hobi', 'Umur']]
# df.loc[:]

"""**13. Siapa saja yang berumur lebih tua dari Eminem? Tampilkan kolom nama dan umur!**"""

# df
eminem_age = df.loc[df.Nama == 'Eminem', 'Umur'].values[0]

df.loc[df.Umur > eminem_age, ['Nama', 'Umur']]