# -*- coding: utf-8 -*-
"""Benjamin Nikholas_Tugas 17_Modul 2_3 Juni 2024.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13wwEqSUgaRi96ga-kgAtDQip2ImJOag0

> Benjamin Nikholas

> Data Science / JCSDOL-014

> Modul 2 - Tugas 17

> 3 Juni 2024
---
---
"""

import numpy as np
import pandas as pd

"""# 1
 Buatlah sebuah array 1 dimensi (vektor) yang diisi dengan 36 elemen. Isi dari array
tersebut adalah bilangan random yang dibangkitkan dari rentang nilai 1 hingga 100.
Simpan array tersebut dalam sebuah variable bernama myArray, kemudian coba
tampilkan!

"""

myArray = np.random.randint(1, 101, size=36)
print(myArray)

"""# 2
 Dari myArray, bentuklah 3 array dengan bentuk yang berbeda (mengganti dimensi
matriksnya) dengan kombinasi ukuran yang berbeda beda!
* Matriks berukuran 2x18
* Matriks berukuran 9x4
* Array 3 Dimensi berukuran 2x6x3
"""

shape_list = [(2, 18), (9, 4), (2, 6, 3)]
for i in shape_list:
  print(f'MyArray Reshape: {i}')
  print(myArray.reshape(i), '\n')

"""# 3
Berapakah nilai minimun dan maksimum dari myArray? Tampilkan dan coba perlihatkan
nilai maksimum dan minimum tersebut ada pada indeks keberapa!
"""

print(f'Nilai Minimum myArray bernilai {myArray.min()} dan berada pada indeks ke {np.where(myArray == myArray.min())}')
print(f'Nilai Maksimum myArray bernilai {myArray.max()} dan berada pada indeks ke {np.where(myArray == myArray.max())}')

"""# 4
Buatlah sebuah array baru dari myArray dengan data yang diambil berasal dari index 3,
5, 30, 12, 15, 8, 24, 14, 22. Setelah itu, reshape bentuknya menjadi sebuah matrix
ukuran 3x3!
"""

idx = [3, 5, 30, 12, 15, 8, 24, 14, 22]

newArray = myArray[idx]
newArray = newArray.reshape(3, 3)
newArray

"""# 5  
Dari matrix yang dibuat pada nomor 4, tampilkan data yang nilainya lebih besar dari 50!
"""

print(newArray[newArray > 50])

"""# 6
Buat sebuah array menggunkan salah satu method di numpy dengan output seperti di
bawah ini!
"""

np.linspace(0, 100,
            num=5,
            dtype = int)

"""# 7
Buatlah sebuah array 2 dimensi dengan ukuran NxN di mana N nya adalah sebuah
inputan. Isi dari array tersebut seluruhnya adalah angka 8!
"""

N = int(input("Masukkan ukuran N: "))

array_NxN = np.full((N, N), 8)
array_NxN

"""# 8
 Buatlah 2 buah array 2 dimensi seperti gambar di bawah ini, lalu simpan dalam variabel
bernama arrayA dan arrayB!
"""

arrayA = np.linspace(1, 12,
                     num = 12,
                     dtype = int).reshape(3, 4)
print(arrayA)

arrayB = np.array([[100], [200], [300], [400]])

print('\n', arrayB)

arrayC = np.vstack((arrayA,
                    arrayB.flatten()))

print('\n', arrayC)

"""# 9
Dari arrayC, lakukan slicing agar menghasilkan array di bawah ini!
"""

arrayC[1:3, 2:4]

"""# 10
Dari arrayC, lakukan indexing untuk mendapatkan angka 200!
"""

arrayC[3,1]