# -*- coding: utf-8 -*-
"""Benjamin Nikholas_Tugas 19_Modul 2_6 Juni 2024.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1eqiGKU8X6pPHdV_yX4TptGA4OHxYEsnp

> Benjamin Nikholas

> Data Science / JCSDOL-014

> Modul 2 - Tugas 19

> 6 Juni 2024
---
---

# Exercise: Pandas
"""

import numpy as np
import pandas as pd

"""1. Load dataset Salaries.csv, kemudian simpan dalam sebuah variabel bernama **df**"""

df = pd.read_csv('Salaries.csv')

"""2. Tampilkan 7 baris pertama dari dataframe df"""

df.head(7)

"""3. Tampilkan informasi dataframe mengenai nama-nama kolom, jumlah data yang terisi, dan tipe datanya"""

df.info()

"""4. Tampilkan karyawan bernama Rosemary Lee dan pekerjaannya"""

df.loc[df.EmployeeName == 'Rosemary Lee', ['EmployeeName', 'JobTitle']]

"""5. Tampilkan nama karyawan dengan TotalPayBenefits paling besar"""

df.loc[df.TotalPayBenefits == df.TotalPayBenefits.max(), 'EmployeeName'].values[0].capitalize()

"""6. Tampilkan dataset diurutkan dari tahun paling tua, kemudian dari BasePay paling besar"""

df.sort_values(by = ['Year', 'BasePay'],
               ascending = [True, False])

"""7. Tampilkan missing values pada kolom BasePay dan OvertimePay"""

print(df.BasePay.isna(), '\n')
print(df.OvertimePay.isna())

"""8. Tampilkan jumlah baris dari dataframe df"""

print(f'Jumlah baris df : {len(df)}')

"""9. Tampilkan karyawan dengan BasePay lebih dari 300 ribu dollar dan OvertimePay-nya bukan 0 dollar"""

df[(df.BasePay > 300000) & (df.OvertimePay != 0)]

"""10. Tampilkan data karyawan yang selisih TotalPayBenefits dan BasePay-nya bernilai negatif"""

df[(df.TotalPayBenefits - df.BasePay < 0) | (df.BasePay - df.TotalPayBenefits < 0)]

"""11. JobTitle apa saja yang hanya muncul 1 kali (hanya dimiliki oleh 1 orang)?"""

df['JobTitle'].value_counts()[df['JobTitle'].value_counts() == 1]

"""12. Berapa median dari TotalPayBenefits pada tahun 2011"""

print(f'Median dari TotalPayBenefits di tahun 2011 : {df[df.Year == 2011].TotalPayBenefits.median()}')