# -*- coding: utf-8 -*-
"""Benjamin Nikholas_Tugas 5_Modul 1_7 Mei 2024.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ByUv-cNDpa4-TKmFzvhi1GyNUutg_PVC

> Benjamin Nikholas

> Data Science / JCSDOL-014

> Modul 1 - Tugas 5

> 7 Mei 2024
---
---

#1 Auto Translator Hari

Silakan buat 1 Dictionary untuk Inisiasi

Hari = {"senin" : "monday",
"selasa" : "tuesday",
"rabu" : "wednesday",
dst....
}

> Input :
* Masukkan Nama Hari :

> Output :
* Jika yg dimasukkan hari dalam bahasa indonesia:

> `nama hari – in English is -hari dalam bahasa inggris-`

*  Jika yg dimasukkan dari dalam bahasa inggris:

> `-hari dalam bahasa inggris- in Bahasa is -hari bahasa indo-`
"""

hari = {
    'senin': 'monday',
    'selasa': 'tuesday',
    'rabu': 'wednesday',
    'kamis': 'thursday',
    'jumat': 'friday',
    'sabtu': 'saturday',
    'minggu': 'sunday'
}

while True:
    day = input('Masukkan Nama Hari: ').lower()

    if day in hari:
        print(f'{day.capitalize()} in English is {hari[day].capitalize()}')
        break
    elif day in hari.values():
        hari_indo = [key for key, value in hari.items() if value == day][0]
        print(f'{day.capitalize()} in Bahasa is {hari_indo.capitalize()}')
        break
    else:
        print('Hari tidak valid.')

"""#2

Kita memiliki daftar Hari

> Input :
* Masukkan nama hari .......YYYY
* Masukkan Jumlah......x

> Output :
* Hari ini hari YYYY, x hari lagi adalah hari ....

"""

days = ['Senin', 'Selasa', 'Rabu', 'Kamis', 'Jumat', 'Sabtu', 'Minggu']

day_input = input('Masukkan nama hari: ')
day_nums = int(input('Masukkan Jumlah hari: '))

day_input = day_input.capitalize()
day_index = days.index(day_input)

future_day_index = (day_index + day_nums) % 7

print(f'Hari ini hari {day_input}, {day_nums} hari lagi adalah hari {days[future_day_index]}')

"""#3
> input : Masukkan kalimat :

> Output : (Reverse per kata)
"""

sentence = input('Masukkan kalimat: ')
words = sentence.split()
reverse_sentence = ''

for word in words:
    reverse_sentence += f'{word[::-1]}'

print(f'Kalimat setelah dibalik per kata: {reverse_sentence}')