# -*- coding: utf-8 -*-
"""Benjamin Nikholas_Tugas 3_Modul 1_2 Mei 2024.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1B_-N0dnaFno8C2JqN4rFu4nlPt47Yegz

> Benjamin Nikholas

> Data Science / JCSDOL-014

> Modul 1 - Tugas 3

> 2 Mei 2024
---
---

#1
"""

def pattern(rows):
    for i in range(1, rows + 1):
        print((str(i) + ' ') * i)

pattern(5)

"""#2"""

def pattern(rows):
    for i in range(1, rows + 1):
        row_string = ""
        for j in range(1, i + 1):
            row_string += str(j) + " "
        print(row_string)

pattern(5)

def pattern(rows):
    for i in range(1, rows + 1):
        for j in range(1, i + 1):
          print(i, j)

pattern(5)

"""#3"""

def pattern(rows):
    for i in range(1, rows + 1):
        row_string = ""
        for j in range(rows, rows - i, -1):
            row_string += str(j) + " "
        print(row_string)

pattern(5)

def pattern(rows):
    for i in range(1, rows + 1):
        for j in range(rows, rows - i, -1):
          print(i, j)

pattern(5)

"""#4"""

def pattern(rows):
    for i in range(1, rows + 1):
        row_string = ""
        for j in range(1, rows - i + 2):
            row_string += str(i) + " "
        print(row_string)

pattern(5)

def pattern(rows):
    for i in range(1, rows + 1):
        for j in range(1, rows - i + 2):
          print(i, j)

pattern(5)

"""#5"""

def pattern(rows):
    for i in range(rows, 0, -1):
        row_string = ""
        for j in range(1, i + 1):
            row_string += str(j) + " "
        print(row_string.rstrip())

pattern(5)

def pattern(rows):
    for i in range(rows, 0, -1):
        for j in range(1, i + 1):
          print(i, j)

pattern(5)

"""#6"""

def pattern(rows):
    for i in range(rows, 0, -1):
        row_string = ""
        for j in range(rows, rows - i, -1):
            row_string += str(j) + " "
        print(row_string.rstrip())

pattern(5)

def pattern(rows):
    for i in range(rows, 0, -1):
        for j in range(rows, rows - i, -1):
          print(i, j)

pattern(5)

